/******************************************************************************
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * This file is part of base.
 * This file is generated by troer, don't edit manually.
 ******************************************************************************/

#ifndef _BASE_H
#define _BASE_H


#include <dpack/codec.h>
#include <dpack/lvstr.h>
#include <errno.h>
#include <hed/priv/config.h>
#include <json-c/json_object.h>
#include <regex.h>
#include <stroll/cdefs.h>

/**
 * Assert if condition is not
 * @def hed_assert(_cond)
 * @param [in] _cond The condition.
 * @see CONFIG_BASE_ASSERT
 */
#if defined(CONFIG_BASE_ASSERT)
# include <stroll/assert.h>
# ifndef hed_assert
#  define hed_assert(_cond) \
           stroll_assert("base", _cond)
# endif
# ifndef __hed_nonull
#  define __hed_nonull(_arg_index, ...)
# endif
#else
# include <stroll/cdefs.h>
# ifndef hed_assert
#  define hed_assert(_cond)
# endif
# ifndef __hed_nonull
#  define __hed_nonull(_arg_index, ...) \
           __nonull(_arg_index, ## __VA_ARGS__)
# endif
#endif

/**
 * Minimum size in bytes of an struct stroll_lvstr serialized according to
 * the @rstsubst{MessagePack int format}.
 */
#define HED_NAME_PACKED_SIZE_MIN DPACK_LVSTR_CONST_SIZE(1)

/**
 * Maximum size in bytes of an struct stroll_lvstr serialized according to
 * the @rstsubst{MessagePack int format}.
 */
#define HED_NAME_PACKED_SIZE_MAX DPACK_LVSTR_CONST_SIZE(40)

/**
 * Check if input is valid struct stroll_lvstr
 *
 * @param[in] value The value to test
 *
 * @return an errno like error code
 * @retval 0       Success
 * @retval -EINVAL Invalid value
 */
extern int
hed_chk_name(const struct stroll_lvstr * value)
	__hed_nonull(1) __warn_result ;

/**
 * Decode a struct stroll_lvstr encoded according to the MessagePack format
 *
 * @param[inout] decoder decoder
 * @param[out]   value   location where to store decoded value
 *
 * @return an errno like error code
 * @retval 0         Success
 * @retval -EPROTO   Not a valid MessagePack stream
 * @retval -ENOTSUP  Unsupported MessagePack stream data
 * @retval -ENOMSG   Invalid MessagePack stream data type or range
 * @retval -EMSGSIZE Not enough space to complete operation
 * @retval -ENOMEM   Memory allocation failure
 *
 * @warning
 * - @p decoder *MUST* have been initialized using dpack_decoder_init_buffer()
 *   or dpack_decoder_init_skip_buffer() before calling this function. Result is
 *   undefined otherwise.
 * - When compiled with the #CONFIG_BASE_ASSERT build option
 *   disabled and @p decoder is in error state before calling this function,
 *   result is undefined. An assertion is triggered otherwise.
 *
 * @see
 * - dpack_decoder_init_buffer()
 * - dpack_decoder_init_skip_buffer()
 */
static inline int __hed_nonull(1, 2) __nothrow __warn_result 
hed_dec_name(struct dpack_decoder * decoder,
	  struct stroll_lvstr * __restrict value)
{
	hed_assert(decoder);
	hed_assert(value);

	ssize_t ret;

	ret = dpack_decode_lvstr_max(decoder, 40, value);
	if (ret < 0)
		return (int)ret;

	return hed_chk_name(value);
};

/**
 * Encode an struct stroll_lvstr according to the MessagePack format
 * @param[inout] encoder encoder
 * @param[in]    value  hed_name value to encode
 *
 * @return an errno like error code
 * @retval 0         Success
 * @retval -EMSGSIZE Not enough space to complete operation
 * @retval -ENOMEM   Memory allocation failure
 *
 * @warning
 * - @p encoder *MUST* have been initialized using dpack_encoder_init_buffer()
 *   before calling this function. Result is undefined otherwise.
 * - When compiled with the #CONFIG_BASE_ASSERT build option
 *   disabled and @p decoder is in error state before calling this function,
 *   result is undefined. An assertion is triggered otherwise.
 *
 * @see
 * - dpack_encode_lvstr()
 * - dpack_encoder_init_buffer()
 */
static inline int __hed_nonull(1, 2) __nothrow __warn_result 
hed_enc_name(struct dpack_encoder * encoder,
	  const struct stroll_lvstr * value)
{
	hed_assert(encoder);
	hed_assert(hed_chk_name(value) == 0);

	return dpack_encode_lvstr(encoder, value);
};

/**
 * Decode a struct stroll_lvstr encoded according to the MessagePack format
 *
 * @param[inout] decoder decoder
 *
 * @return an json-c object or NULL if error
 * @retval NULL      Error setted in errno.
 * @retval -EPROTO   Not a valid MessagePack stream
 * @retval -ENOTSUP  Unsupported MessagePack stream data
 * @retval -ENOMSG   Invalid MessagePack stream data type or range
 * @retval -EMSGSIZE Not enough space to complete operation
 * @retval -ENOMEM   Memory allocation failure
 *
 * @warning
 * - @p decoder *MUST* have been initialized using dpack_decoder_init_buffer()
 *   or dpack_decoder_init_skip_buffer() before calling this function. Result is
 *   undefined otherwise.
 * - When compiled with the #CONFIG_BASE_ASSERT build option
 *   disabled and @p decoder is in error state before calling this function,
 *   result is undefined. An assertion is triggered otherwise.
 *
 * @see
 * - dpack_decoder_init_buffer()
 * - dpack_decoder_init_skip_buffer()
 */
extern struct json_object *
hed_dec_name_to_json(struct dpack_decoder * decoder)
__hed_nonull(1) __nothrow __warn_result ;

/**
 * Encode an json struct stroll_lvstr according to the MessagePack format
 * @param[inout] encoder encoder
 * @param[in]    object json-object value to encode
 *
 * @return an errno like error code
 * @retval 0         Success
 * @retval -EMSGSIZE Not enough space to complete operation
 * @retval -ENOMEM   Memory allocation failure
 * @retval -EINVAL   Invalid value
 *
 * @warning
 * - @p encoder *MUST* have been initialized using dpack_encoder_init_buffer()
 *   before calling this function. Result is undefined otherwise.
 * - When compiled with the #CONFIG_BASE_ASSERT build option
 *   disabled and @p decoder is in error state before calling this function,
 *   result is undefined. An assertion is triggered otherwise.
 *
 * @see
 * - dpack_encode_lvstr()
 * - dpack_encoder_init_buffer()
 */
extern int
hed_enc_name_from_json(struct dpack_encoder * encoder,
		    struct json_object * object)
__hed_nonull(1, 2) __nothrow __warn_result ;

/*
 * Initialize an empty stroll_lvstr_.
 * @param[out] value Length-Value String
 *
 * @return an arrno like error code
 * @retval 0         Success
 *
 * @see
 * - stroll_lvstr_init()
 */
static inline int __hed_nonull(1) __warn_result 
hed_init_name(struct stroll_lvstr * value)
{
	hed_assert(value);

	stroll_lvstr_init(value);
	return 0;
};

/*
 * Finalize an empty stroll_lvstr_.
 * @param[inout] value Length-Value String
 *
 * @see
 * - stroll_lvstr_fini()
 */
static inline void __hed_nonull(1) 
hed_fini_name(struct stroll_lvstr * value)
{
	hed_assert(value);

	stroll_lvstr_fini(value);
};

#endif /* _BASE_H */
