/******************************************************************************
 * SPDX-License-Identifier: MIT-0
 *
 * This file is part of base.
 * This file is generated by troer, don't edit manually.
 ******************************************************************************/

#ifndef _HED_BASE_H
#define _HED_BASE_H


#include <dpack/codec.h>
#include <dpack/lvstr.h>
#include <dpack/scalar.h>
#include <errno.h>
#include <hed/priv/config.h>
#include <json-c/json_object.h>
#include <regex.h>
#include <string.h>
#include <stroll/array.h>
#include <stroll/cdefs.h>

/**
 * Assert if condition is not
 * @def hed_assert(_cond)
 * @param [in] _cond The condition.
 * @see CONFIG_BASE_ASSERT
 */
#if defined(CONFIG_BASE_ASSERT)
# include <stroll/assert.h>
# ifndef hed_assert
#  define hed_assert(_cond) \
           stroll_assert("base", _cond)
# endif
# ifndef __hed_nonull
#  define __hed_nonull(_arg_index, ...)
# endif
#else
# include <stroll/cdefs.h>
# ifndef hed_assert
#  define hed_assert(_cond)
# endif
# ifndef __hed_nonull
#  define __hed_nonull(_arg_index, ...) \
           __nonull(_arg_index, ## __VA_ARGS__)
# endif
#endif

/**
 * Minimum size in bytes of an struct stroll_lvstr serialized according to
 * the @rstsubst{MessagePack int format}.
 */
#define HED_NAME_PACKED_SIZE_MIN DPACK_LVSTR_CONST_SIZE(1)

/**
 * Maximum size in bytes of an struct stroll_lvstr serialized according to
 * the @rstsubst{MessagePack int format}.
 */
#define HED_NAME_PACKED_SIZE_MAX DPACK_LVSTR_CONST_SIZE(40)

/**
 * Check if input is valid struct stroll_lvstr
 *
 * @param[in] value The value to test
 *
 * @return an errno like error code
 * @retval 0       Success
 * @retval -EINVAL Invalid value
 */
extern int
hed_chk_name(const struct stroll_lvstr * value)
	__hed_nonull(1) __warn_result ;

/**
 * Decode a struct stroll_lvstr encoded according to the MessagePack format
 *
 * @param[inout] decoder decoder
 * @param[out]   value   location where to store decoded value
 *
 * @return an errno like error code
 * @retval 0         Success
 * @retval -EPROTO   Not a valid MessagePack stream
 * @retval -ENOTSUP  Unsupported MessagePack stream data
 * @retval -ENOMSG   Invalid MessagePack stream data type or range
 * @retval -EMSGSIZE Not enough space to complete operation
 * @retval -ENOMEM   Memory allocation failure
 *
 * @warning
 * - @p decoder *MUST* have been initialized using dpack_decoder_init_buffer()
 *   or dpack_decoder_init_skip_buffer() before calling this function. Result is
 *   undefined otherwise.
 * - When compiled with the #CONFIG_BASE_ASSERT build option
 *   disabled and @p decoder is in error state before calling this function,
 *   result is undefined. An assertion is triggered otherwise.
 *
 * @see
 * - dpack_decoder_init_buffer()
 * - dpack_decoder_init_skip_buffer()
 */
static inline int __hed_nonull(1, 2) __nothrow __warn_result 
hed_dec_name(struct dpack_decoder * decoder,
	  struct stroll_lvstr * __restrict value)
{
	hed_assert(decoder);
	hed_assert(value);

	ssize_t ret;

	ret = dpack_decode_lvstr_max(decoder, 40, value);
	if (ret < 0)
		return (int)ret;

	return hed_chk_name(value);
};

/**
 * Encode an struct stroll_lvstr according to the MessagePack format
 * @param[inout] encoder encoder
 * @param[in]    value  hed_name value to encode
 *
 * @return an errno like error code
 * @retval 0         Success
 * @retval -EMSGSIZE Not enough space to complete operation
 * @retval -ENOMEM   Memory allocation failure
 *
 * @warning
 * - @p encoder *MUST* have been initialized using dpack_encoder_init_buffer()
 *   before calling this function. Result is undefined otherwise.
 * - When compiled with the #CONFIG_BASE_ASSERT build option
 *   disabled and @p decoder is in error state before calling this function,
 *   result is undefined. An assertion is triggered otherwise.
 *
 * @see
 * - dpack_encode_lvstr()
 * - dpack_encoder_init_buffer()
 */
static inline int __hed_nonull(1, 2) __nothrow __warn_result 
hed_enc_name(struct dpack_encoder * encoder,
	  const struct stroll_lvstr * value)
{
	hed_assert(encoder);
	hed_assert(hed_chk_name(value) == 0);

	return dpack_encode_lvstr(encoder, value);
};

/**
 * Decode a struct stroll_lvstr encoded according to the MessagePack format
 *
 * @param[inout] decoder decoder
 *
 * @return an json-c object or NULL if error
 * @retval NULL      Error setted in errno.
 * @retval -EPROTO   Not a valid MessagePack stream
 * @retval -ENOTSUP  Unsupported MessagePack stream data
 * @retval -ENOMSG   Invalid MessagePack stream data type or range
 * @retval -EMSGSIZE Not enough space to complete operation
 * @retval -ENOMEM   Memory allocation failure
 *
 * @warning
 * - @p decoder *MUST* have been initialized using dpack_decoder_init_buffer()
 *   or dpack_decoder_init_skip_buffer() before calling this function. Result is
 *   undefined otherwise.
 * - When compiled with the #CONFIG_BASE_ASSERT build option
 *   disabled and @p decoder is in error state before calling this function,
 *   result is undefined. An assertion is triggered otherwise.
 *
 * @see
 * - dpack_decoder_init_buffer()
 * - dpack_decoder_init_skip_buffer()
 */
extern struct json_object *
hed_dec_name_to_json(struct dpack_decoder * decoder)
__hed_nonull(1) __nothrow __warn_result ;

/**
 * Encode an json struct stroll_lvstr according to the MessagePack format
 * @param[inout] encoder encoder
 * @param[in]    object json-object value to encode
 *
 * @return an errno like error code
 * @retval 0         Success
 * @retval -EMSGSIZE Not enough space to complete operation
 * @retval -ENOMEM   Memory allocation failure
 * @retval -EINVAL   Invalid value
 *
 * @warning
 * - @p encoder *MUST* have been initialized using dpack_encoder_init_buffer()
 *   before calling this function. Result is undefined otherwise.
 * - When compiled with the #CONFIG_BASE_ASSERT build option
 *   disabled and @p decoder is in error state before calling this function,
 *   result is undefined. An assertion is triggered otherwise.
 *
 * @see
 * - dpack_encode_lvstr()
 * - dpack_encoder_init_buffer()
 */
extern int
hed_enc_name_from_json(struct dpack_encoder * encoder,
		    struct json_object * object)
__hed_nonull(1, 2) __nothrow __warn_result ;

/*
 * Initialize an empty stroll_lvstr_.
 * @param[out] value Length-Value String
 *
 * @return an arrno like error code
 * @retval 0         Success
 *
 * @see
 * - stroll_lvstr_init()
 */
static inline int __hed_nonull(1) __warn_result 
hed_init_name(struct stroll_lvstr * value)
{
	hed_assert(value);

	stroll_lvstr_init(value);
	return 0;
};

/*
 * Finalize an empty stroll_lvstr_.
 * @param[inout] value Length-Value String
 *
 * @see
 * - stroll_lvstr_fini()
 */
static inline void __hed_nonull(1) 
hed_fini_name(struct stroll_lvstr * value)
{
	hed_assert(value);

	stroll_lvstr_fini(value);
};






/**
 * Minimum size in bytes of an enum hed_bauds serialized according to
 * the @rstsubst{MessagePack int format}.
 */
#define HED_BAUDS_PACKED_SIZE_MIN DPACK_INT_SIZE_MIN

/**
 * Maximum size in bytes of an enum hed_bauds serialized according to
 * the @rstsubst{MessagePack int format}.
 */
#define HED_BAUDS_PACKED_SIZE_MAX DPACK_INT_SIZE_MAX

/**
 * Number of elements in the enum hed_bauds
 */
#define HED_BAUDS_NB 5

/**
 * @enum hed_bauds
 * 
 **/
enum hed_bauds {
		HED_BD_9600 = 9600,
		HED_BD_19200 = 19200,
		HED_BD_38400 = 38400,
		HED_BD_57600 = 57600,
		HED_BD_115200 = 115200,
};

/**
 * Convert enum hed_bauds to string format
 *
 * @param[in] value The value to convert
 *
 * @return a const string
 * @return NULL Invalid value
 */
extern const char *
hed_bauds_to_str(enum hed_bauds value)
__warn_result ;

/**
 * Search a string format of enum hed_bauds
 *
 * @param[in]  str   The string to research
 * @param[out] value The value founding
 *
 * @return an errno like error code
 * @retval 0       Success
 * @retval -EINVAL Invalid value
 */
extern int
hed_bauds_from_str(const char *str, enum hed_bauds *value)
 __hed_nonull(1, 2) __warn_result ;

/**
 * Copy to array all pointer constant string of enum hed_bauds
 *
 * @param[in] buf The buffer to copy
 * @param[in] nr  The buffer size
 *
 * @return number of elements added
 *
 * @warning
 * - When compiled with the #CONFIG_BASE_ASSERT build option
 *   disabled and @p nr is lower than #HED_BAUDS_NB value, the
 *   result is undefined. An assertion is triggered otherwise.
 *
 * @see HED_BAUDS_NB
 */
extern int
hed_bauds_dump_str(const char ** buf, size_t nr)
 __hed_nonull(1) ;

/**
 * Check if input is valid enum hed_bauds
 *
 * @param[in] value The value to test
 *
 * @return an errno like error code
 * @retval 0       Success
 * @retval -EINVAL Invalid value
 */
static inline int __warn_result 
hed_chk_bauds(enum hed_bauds value)
{
	if (hed_bauds_to_str(value) == NULL)
		return -EINVAL;

	return 0;
};

/**
 * Decode a enum hed_bauds encoded according to the MessagePack format
 *
 * @param[inout] decoder decoder
 * @param[out]   value   location where to store decoded value
 *
 * @return an errno like error code
 * @retval 0         Success
 * @retval -EPROTO   Not a valid MessagePack stream
 * @retval -ENOTSUP  Unsupported MessagePack stream data
 * @retval -ENOMSG   Invalid MessagePack stream data type or range
 * @retval -EMSGSIZE Not enough space to complete operation
 * @retval -ENOMEM   Memory allocation failure
 *
 * @warning
 * - @p decoder *MUST* have been initialized using dpack_decoder_init_buffer()
 *   or dpack_decoder_init_skip_buffer() before calling this function. Result is
 *   undefined otherwise.
 * - When compiled with the #CONFIG_BASE_ASSERT build option
 *   disabled and @p decoder is in error state before calling this function,
 *   result is undefined. An assertion is triggered otherwise.
 *
 * @sa
 * - dpack_decoder_init_buffer()
 * - dpack_decoder_init_skip_buffer()
 */
static inline int __hed_nonull(1, 2) __nothrow __warn_result 
hed_dec_bauds(struct dpack_decoder * decoder,
	  enum hed_bauds * __restrict value)
{
	hed_assert(decoder);
	hed_assert(value);

	int ret;

	ret = dpack_decode_int(decoder, (int *)value);
	if (ret)
		return ret;

	return hed_chk_bauds(*value);
};

/**
 * Encode an enum hed_bauds according to the MessagePack format
 * @param[inout] encoder encoder
 * @param[in]    value   enum hed_bauds value to encode
 *
 * @return an errno like error code
 * @retval 0         Success
 * @retval -EMSGSIZE Not enough space to complete operation
 * @retval -ENOMEM   Memory allocation failure
 *
 * @warning
 * - @p encoder *MUST* have been initialized using dpack_encoder_init_buffer()
 *   before calling this function. Result is undefined otherwise.
 * - When compiled with the #CONFIG_BASE_ASSERT build option
 *   disabled and @p decoder is in error state before calling this function,
 *   result is undefined. An assertion is triggered otherwise.
 *
 * @see
 * - dpack_encode_int8()
 * - dpack_encoder_init_buffer()
 */
static inline int __hed_nonull(1) __nothrow __warn_result 
hed_enc_bauds(struct dpack_encoder * encoder,
	  enum hed_bauds value)
{
	hed_assert(encoder);

	return dpack_encode_int(encoder, (int)value);
};

/**
 * Decode a int encoded according to the MessagePack format
 *
 * @param[inout] decoder decoder
 *
 * @return an json-c object or NULL if error
 * @retval NULL      Error setted in errno.
 * @retval -EPROTO   Not a valid MessagePack stream
 * @retval -ENOTSUP  Unsupported MessagePack stream data
 * @retval -ENOMSG   Invalid MessagePack stream data type or range
 * @retval -EMSGSIZE Not enough space to complete operation
 * @retval -ENOMEM   Memory allocation failure
 *
 * @warning
 * - @p decoder *MUST* have been initialized using dpack_decoder_init_buffer()
 *   or dpack_decoder_init_skip_buffer() before calling this function. Result is
 *   undefined otherwise.
 * - When compiled with the #CONFIG_BASE_ASSERT build option
 *   disabled and @p decoder is in error state before calling this function,
 *   result is undefined. An assertion is triggered otherwise.
 *
 * @see
 * - dpack_decoder_init_buffer()
 * - dpack_decoder_init_skip_buffer()
 */
extern struct json_object *
hed_dec_bauds_to_json(struct dpack_decoder * decoder)
__hed_nonull(1) __nothrow __warn_result ;

/**
 * Encode an json string according to the MessagePack format
 * @param[inout] encoder encoder
 * @param[in]    object  json-object value to encode
 *
 * @return an errno like error code
 * @retval 0         Success
 * @retval -EMSGSIZE Not enough space to complete operation
 * @retval -ENOMEM   Memory allocation failure
 * @retval -EINVAL   Invalid value
 *
 * @warning
 * - @p encoder *MUST* have been initialized using dpack_encoder_init_buffer()
 *   before calling this function. Result is undefined otherwise.
 * - When compiled with the #CONFIG_BASE_ASSERT build option
 *   disabled and @p decoder is in error state before calling this function,
 *   result is undefined. An assertion is triggered otherwise.
 *
 * @see
 * - dpack_encode_()
 * - dpack_encoder_init_buffer()
 */
extern int
hed_enc_bauds_from_json(struct dpack_encoder * encoder,
		    struct json_object * object)
__hed_nonull(1, 2) __nothrow __warn_result ;




/**
 * Minimum size in bytes of an enum hed_toggle serialized according to
 * the @rstsubst{MessagePack int format}.
 */
#define HED_TOGGLE_PACKED_SIZE_MIN DPACK_INT_SIZE_MIN

/**
 * Maximum size in bytes of an enum hed_toggle serialized according to
 * the @rstsubst{MessagePack int format}.
 */
#define HED_TOGGLE_PACKED_SIZE_MAX DPACK_INT_SIZE_MAX

/**
 * Number of elements in the enum hed_toggle
 */
#define HED_TOGGLE_NB 2

/**
 * @enum hed_toggle
 * 
 **/
enum hed_toggle {
		HED_DISABLE = 0,
		HED_ENABLE = 1,
};

/**
 * Convert enum hed_toggle to string format
 *
 * @param[in] value The value to convert
 *
 * @return a const string
 * @return NULL Invalid value
 */
extern const char *
hed_toggle_to_str(enum hed_toggle value)
__warn_result ;

/**
 * Search a string format of enum hed_toggle
 *
 * @param[in]  str   The string to research
 * @param[out] value The value founding
 *
 * @return an errno like error code
 * @retval 0       Success
 * @retval -EINVAL Invalid value
 */
extern int
hed_toggle_from_str(const char *str, enum hed_toggle *value)
 __hed_nonull(1, 2) __warn_result ;

/**
 * Copy to array all pointer constant string of enum hed_toggle
 *
 * @param[in] buf The buffer to copy
 * @param[in] nr  The buffer size
 *
 * @return number of elements added
 *
 * @warning
 * - When compiled with the #CONFIG_BASE_ASSERT build option
 *   disabled and @p nr is lower than #HED_TOGGLE_NB value, the
 *   result is undefined. An assertion is triggered otherwise.
 *
 * @see HED_TOGGLE_NB
 */
extern int
hed_toggle_dump_str(const char ** buf, size_t nr)
 __hed_nonull(1) ;

/**
 * Check if input is valid enum hed_toggle
 *
 * @param[in] value The value to test
 *
 * @return an errno like error code
 * @retval 0       Success
 * @retval -EINVAL Invalid value
 */
static inline int __warn_result 
hed_chk_toggle(enum hed_toggle value)
{
	if (hed_toggle_to_str(value) == NULL)
		return -EINVAL;

	return 0;
};

/**
 * Decode a enum hed_toggle encoded according to the MessagePack format
 *
 * @param[inout] decoder decoder
 * @param[out]   value   location where to store decoded value
 *
 * @return an errno like error code
 * @retval 0         Success
 * @retval -EPROTO   Not a valid MessagePack stream
 * @retval -ENOTSUP  Unsupported MessagePack stream data
 * @retval -ENOMSG   Invalid MessagePack stream data type or range
 * @retval -EMSGSIZE Not enough space to complete operation
 * @retval -ENOMEM   Memory allocation failure
 *
 * @warning
 * - @p decoder *MUST* have been initialized using dpack_decoder_init_buffer()
 *   or dpack_decoder_init_skip_buffer() before calling this function. Result is
 *   undefined otherwise.
 * - When compiled with the #CONFIG_BASE_ASSERT build option
 *   disabled and @p decoder is in error state before calling this function,
 *   result is undefined. An assertion is triggered otherwise.
 *
 * @sa
 * - dpack_decoder_init_buffer()
 * - dpack_decoder_init_skip_buffer()
 */
static inline int __hed_nonull(1, 2) __nothrow __warn_result 
hed_dec_toggle(struct dpack_decoder * decoder,
	  enum hed_toggle * __restrict value)
{
	hed_assert(decoder);
	hed_assert(value);

	int ret;

	ret = dpack_decode_int(decoder, (int *)value);
	if (ret)
		return ret;

	return hed_chk_toggle(*value);
};

/**
 * Encode an enum hed_toggle according to the MessagePack format
 * @param[inout] encoder encoder
 * @param[in]    value   enum hed_toggle value to encode
 *
 * @return an errno like error code
 * @retval 0         Success
 * @retval -EMSGSIZE Not enough space to complete operation
 * @retval -ENOMEM   Memory allocation failure
 *
 * @warning
 * - @p encoder *MUST* have been initialized using dpack_encoder_init_buffer()
 *   before calling this function. Result is undefined otherwise.
 * - When compiled with the #CONFIG_BASE_ASSERT build option
 *   disabled and @p decoder is in error state before calling this function,
 *   result is undefined. An assertion is triggered otherwise.
 *
 * @see
 * - dpack_encode_int8()
 * - dpack_encoder_init_buffer()
 */
static inline int __hed_nonull(1) __nothrow __warn_result 
hed_enc_toggle(struct dpack_encoder * encoder,
	  enum hed_toggle value)
{
	hed_assert(encoder);

	return dpack_encode_int(encoder, (int)value);
};

/**
 * Decode a int encoded according to the MessagePack format
 *
 * @param[inout] decoder decoder
 *
 * @return an json-c object or NULL if error
 * @retval NULL      Error setted in errno.
 * @retval -EPROTO   Not a valid MessagePack stream
 * @retval -ENOTSUP  Unsupported MessagePack stream data
 * @retval -ENOMSG   Invalid MessagePack stream data type or range
 * @retval -EMSGSIZE Not enough space to complete operation
 * @retval -ENOMEM   Memory allocation failure
 *
 * @warning
 * - @p decoder *MUST* have been initialized using dpack_decoder_init_buffer()
 *   or dpack_decoder_init_skip_buffer() before calling this function. Result is
 *   undefined otherwise.
 * - When compiled with the #CONFIG_BASE_ASSERT build option
 *   disabled and @p decoder is in error state before calling this function,
 *   result is undefined. An assertion is triggered otherwise.
 *
 * @see
 * - dpack_decoder_init_buffer()
 * - dpack_decoder_init_skip_buffer()
 */
extern struct json_object *
hed_dec_toggle_to_json(struct dpack_decoder * decoder)
__hed_nonull(1) __nothrow __warn_result ;

/**
 * Encode an json string according to the MessagePack format
 * @param[inout] encoder encoder
 * @param[in]    object  json-object value to encode
 *
 * @return an errno like error code
 * @retval 0         Success
 * @retval -EMSGSIZE Not enough space to complete operation
 * @retval -ENOMEM   Memory allocation failure
 * @retval -EINVAL   Invalid value
 *
 * @warning
 * - @p encoder *MUST* have been initialized using dpack_encoder_init_buffer()
 *   before calling this function. Result is undefined otherwise.
 * - When compiled with the #CONFIG_BASE_ASSERT build option
 *   disabled and @p decoder is in error state before calling this function,
 *   result is undefined. An assertion is triggered otherwise.
 *
 * @see
 * - dpack_encode_()
 * - dpack_encoder_init_buffer()
 */
extern int
hed_enc_toggle_from_json(struct dpack_encoder * encoder,
		    struct json_object * object)
__hed_nonull(1, 2) __nothrow __warn_result ;


#endif /* _HED_BASE_H */
