/******************************************************************************
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * This file is part of inet.
 * This file is generated by troer, don't edit manually.
 ******************************************************************************/

#ifndef _INET_H
#define _INET_H


#include <dpack/codec.h>
#include <errno.h>
#include <hed/priv/config.h>
#include <hed/priv/inet.h>
#include <json-c/json_object.h>
#include <stroll/cdefs.h>

/**
 * Assert if condition is not
 * @def hed_assert(_cond)
 * @param [in] _cond The condition.
 * @see CONFIG_INET_ASSERT
 */
#if defined(CONFIG_INET_ASSERT)
# include <stroll/assert.h>
# ifndef hed_assert
#  define hed_assert(_cond) \
           stroll_assert("inet", _cond)
# endif
# ifndef __hed_nonull
#  define __hed_nonull(_arg_index, ...)
# endif
#else
# include <stroll/cdefs.h>
# ifndef hed_assert
#  define hed_assert(_cond)
# endif
# ifndef __hed_nonull
#  define __hed_nonull(_arg_index, ...) \
           __nonull(_arg_index, 
# endif
#endif

/**
 * Minimum size in bytes of an struct ether_addr serialized according to
 * the @rstsubst{MessagePack int format}.
 */
#define HED_ETHER_ADDR_PACKED_SIZE_MIN (DPACK_BIN_SIZE(ETH_ALEN))
	
/**
 * Maximum size in bytes of an struct ether_addr serialized according to
 * the @rstsubst{MessagePack int format}.
 */
#define HED_ETHER_ADDR_PACKED_SIZE_MAX (DPACK_BIN_SIZE(ETH_ALEN))


/**
 * Minimum size in bytes of an struct in_addr serialized according to
 * the @rstsubst{MessagePack int format}.
 */
#define HED_IN_ADDR_PACKED_SIZE_MIN (DPACK_UINT_SIZE_MIN)
	
/**
 * Maximum size in bytes of an struct in_addr serialized according to
 * the @rstsubst{MessagePack int format}.
 */
#define HED_IN_ADDR_PACKED_SIZE_MAX (DPACK_UINT_SIZE_MAX)


/**
 * Minimum size in bytes of an struct in6_addr serialized according to
 * the @rstsubst{MessagePack int format}.
 */
#define HED_IN6_ADDR_PACKED_SIZE_MIN (DPACK_BIN_SIZE(16))
	
/**
 * Maximum size in bytes of an struct in6_addr serialized according to
 * the @rstsubst{MessagePack int format}.
 */
#define HED_IN6_ADDR_PACKED_SIZE_MAX (DPACK_BIN_SIZE(16))


#endif /* _INET_H */
