/******************************************************************************
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * This file is part of base.
 * This file is generated by troer, don't edit manually.
 ******************************************************************************/

#include <hed/base.h>

extern int __hed_nonull(1) __warn_result 
hed_chk_name(const struct stroll_lvstr * value)
{
	hed_assert(value);

	pcre2_code *re;
	pcre2_match_data *match_data;
	int err;
	int errornumber;
	PCRE2_SIZE erroroffset;

	if (40 < stroll_lvstr_len(value))
		return -EINVAL;

	re = pcre2_compile((PCRE2_SPTR)"[a-zA-Z][a-zA-Z0-9_]*",
			   PCRE2_ZERO_TERMINATED,
			   0,
			   &errornumber,
			   &erroroffset,
			   NULL);
	hed_assert(re);
	if (!re)
		return -EAGAIN;

	match_data = pcre2_match_data_create_from_pattern(re, NULL);
	err = pcre2_match(re,
			  (PCRE2_SPTR)stroll_lvstr_cstr(value),
			  PCRE2_ZERO_TERMINATED,
			  0,
			  PCRE2_ANCHORED | PCRE2_ENDANCHORED,
			  match_data,
			  NULL);
	pcre2_code_free(re);
	pcre2_match_data_free(match_data);
	if (err < 0)
		return -EINVAL;

	return 0;
}


