/******************************************************************************
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * This file is part of base.
 * This file is generated by troer, don't edit manually.
 ******************************************************************************/

#include <hed/base.h>


extern struct json_object * __hed_nonull(1) __nothrow __warn_result 
hed_dec_name_to_json(struct dpack_decoder * decoder)
{
	hed_assert(decoder);

	int ret = 0;
	ssize_t len;
	struct stroll_lvstr value;
	struct json_object *obj = NULL;

	ret = hed_init_name(&value);
	if (ret) {
		errno = -ret;
		return NULL;
	}

	len = dpack_decode_lvstr(decoder, &value);
	if (len < 0) {
		errno = (int)-len;
		goto error;
	}

	ret = hed_chk_name(&value);
	if (ret) {
		errno = -ret;
		goto error;
	}

	obj = json_object_new_string(stroll_lvstr_cstr(&value));
error:
	hed_fini_name(&value);
	return obj;
};

extern int __hed_nonull(1, 2) __nothrow __warn_result 
hed_enc_name_from_json(struct dpack_encoder * encoder,
		    struct json_object * object)
{
	hed_assert(encoder);
	hed_assert(object);

	int ret = 0;
	struct stroll_lvstr value;
	const char * str;

	if (!json_object_is_type(object, json_type_string))
		return -EINVAL;

	ret = hed_init_name(&value);
	if (ret)
		return ret;

	str = json_object_get_string(object);
	hed_assert(str);

	ret = stroll_lvstr_lend(&value, str);
	if (ret)
		goto error;

	ret = hed_chk_name(&value);
	if (ret)
		goto error;

	ret = dpack_encode_lvstr(encoder, &value);
error:
	hed_fini_name(&value);
	return ret;
};

