/******************************************************************************
 * SPDX-License-Identifier: MIT-0
 *
 * This file is part of base.
 * This file is generated by troer, don't edit manually.
 ******************************************************************************/

#include <hed/base.h>

int
hed_chk_name(const struct stroll_lvstr * value)
{
	hed_assert(value);

	regex_t regex;
	int ret;

	if (40 < stroll_lvstr_len(value))
		return -EINVAL;

	ret = regcomp(&regex, "^[a-zA-Z][a-zA-Z0-9_]*$", REG_EXTENDED | REG_NOSUB);
	if (ret)
		return -ret;

	ret = regexec(&regex, stroll_lvstr_cstr(value), 0, NULL, REG_NOTBOL | REG_NOTEOL);
	regfree(&regex);
	if (!ret)
		return -EINVAL;
	return 0;
}


