/******************************************************************************
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * This file is part of inet.
 * This file is generated by troer, don't edit manually.
 ******************************************************************************/

#include <hed/inet.h>







extern struct json_object * __hed_nonull(1) __nothrow __warn_result 
hed_dec_ip_type_to_json(struct dpack_decoder * decoder)
{
	hed_assert(decoder);

	int ret;
	enum hed_ip_type value;
	const char *str;

	ret = dpack_decode_int(decoder, (int *)&value);
	if (ret) {
		errno = -ret;
		return NULL;
	}

	str = hed_ip_type_to_str(value);
	if (!str) {
		errno = EINVAL;
		return NULL;
	}
	return json_object_new_string(str);
};

extern int __hed_nonull(1, 2) __nothrow __warn_result 
hed_enc_ip_type_from_json(struct dpack_encoder * encoder,
		    struct json_object * object)
{
	hed_assert(encoder);
	hed_assert(object);

	int ret;
	const char * str;
	enum hed_ip_type value;

	errno = 0;
	str = json_object_get_string(object);
	if (errno)
		return -errno;

	ret = hed_ip_type_from_str(str, &value);
	if (ret)
		return ret;

	return dpack_encode_int(encoder, (int)value);
};

extern struct json_object * __hed_nonull(1) __nothrow __warn_result 
hed_dec_in_pfx_to_json(struct dpack_decoder * decoder)
{
	hed_assert(decoder);

	int ret;
	uint8_t value;

	ret = dpack_decode_uint8(decoder, &value);
	if (ret) {
		errno = -ret;
		return NULL;
	}

	ret = hed_chk_in_pfx(value);
	if (ret) {
		errno = -ret;
		return NULL;
	}

	return json_object_new_int(value);
};

extern int __hed_nonull(1, 2) __nothrow __warn_result 
hed_enc_in_pfx_from_json(struct dpack_encoder * encoder,
		    struct json_object * object)
{
	hed_assert(encoder);
	hed_assert(object);

	int ret;
	uint8_t value;

	errno = 0;
	value = (uint8_t)json_object_get_int(object);
	if (errno)
		return -errno;

	ret = hed_chk_in_pfx(value);
	if (ret)
		return ret;

	return dpack_encode_uint8(encoder, value);
};

extern struct json_object * __hed_nonull(1) __nothrow __warn_result 
hed_dec_in6_pfx_to_json(struct dpack_decoder * decoder)
{
	hed_assert(decoder);

	int ret;
	uint8_t value;

	ret = dpack_decode_uint8(decoder, &value);
	if (ret) {
		errno = -ret;
		return NULL;
	}

	ret = hed_chk_in6_pfx(value);
	if (ret) {
		errno = -ret;
		return NULL;
	}

	return json_object_new_int(value);
};

extern int __hed_nonull(1, 2) __nothrow __warn_result 
hed_enc_in6_pfx_from_json(struct dpack_encoder * encoder,
		    struct json_object * object)
{
	hed_assert(encoder);
	hed_assert(object);

	int ret;
	uint8_t value;

	errno = 0;
	value = (uint8_t)json_object_get_int(object);
	if (errno)
		return -errno;

	ret = hed_chk_in6_pfx(value);
	if (ret)
		return ret;

	return dpack_encode_uint8(encoder, value);
};

extern struct json_object * __hed_nonull(1) __nothrow __warn_result 
hed_dec_port_to_json(struct dpack_decoder * decoder)
{
	hed_assert(decoder);

	int ret;
	uint16_t value;

	ret = dpack_decode_uint16(decoder, &value);
	if (ret) {
		errno = -ret;
		return NULL;
	}

	ret = hed_chk_port(value);
	if (ret) {
		errno = -ret;
		return NULL;
	}

	return json_object_new_int(value);
};

extern int __hed_nonull(1, 2) __nothrow __warn_result 
hed_enc_port_from_json(struct dpack_encoder * encoder,
		    struct json_object * object)
{
	hed_assert(encoder);
	hed_assert(object);

	int ret;
	uint16_t value;

	errno = 0;
	value = (uint16_t)json_object_get_int(object);
	if (errno)
		return -errno;

	ret = hed_chk_port(value);
	if (ret)
		return ret;

	return dpack_encode_uint16(encoder, value);
};



extern struct json_object * __hed_nonull(1) __nothrow __warn_result 
hed_dec_in_svc_to_json(struct dpack_decoder * decoder)
{
	hed_assert(decoder);

	int ret;
	struct json_object *object;
	struct json_object *obj;

	object = json_object_new_object();
	if (!object)
		return NULL;

	obj = hed_decode_in_addr_to_json(decoder);
	if (!obj)
		goto error;

	ret = json_object_object_add(object, "addr", obj);
	if (ret)
		goto error;

	obj = hed_dec_port_to_json(decoder);
	if (!obj)
		goto error;

	ret = json_object_object_add(object, "port", obj);
	if (ret)
		goto error;

	return object;
error:
	json_object_put(object);
	return NULL;
}

extern int __hed_nonull(1, 2) __nothrow __warn_result 
hed_enc_in_svc_from_json(struct dpack_encoder * encoder,
		    struct json_object * object)
{
	hed_assert(encoder);
	hed_assert(object);

	int ret;
	struct json_object *obj;
	size_t nb __unused;

	obj = json_object_object_get(object, "addr");
	if (!obj)
		return -EINVAL;

	ret = hed_encode_in_addr_from_json(encoder, obj);
	if (ret)
		return ret;

	obj = json_object_object_get(object, "port");
	if (!obj)
		return -EINVAL;

	ret = hed_enc_port_from_json(encoder, obj);
	if (ret)
		return ret;

	return 0;
}



extern struct json_object * __hed_nonull(1) __nothrow __warn_result 
hed_dec_in6_svc_to_json(struct dpack_decoder * decoder)
{
	hed_assert(decoder);

	int ret;
	struct json_object *object;
	struct json_object *obj;

	object = json_object_new_object();
	if (!object)
		return NULL;

	obj = hed_decode_in6_addr_to_json(decoder);
	if (!obj)
		goto error;

	ret = json_object_object_add(object, "addr", obj);
	if (ret)
		goto error;

	obj = hed_dec_port_to_json(decoder);
	if (!obj)
		goto error;

	ret = json_object_object_add(object, "port", obj);
	if (ret)
		goto error;

	return object;
error:
	json_object_put(object);
	return NULL;
}

extern int __hed_nonull(1, 2) __nothrow __warn_result 
hed_enc_in6_svc_from_json(struct dpack_encoder * encoder,
		    struct json_object * object)
{
	hed_assert(encoder);
	hed_assert(object);

	int ret;
	struct json_object *obj;
	size_t nb __unused;

	obj = json_object_object_get(object, "addr");
	if (!obj)
		return -EINVAL;

	ret = hed_encode_in6_addr_from_json(encoder, obj);
	if (ret)
		return ret;

	obj = json_object_object_get(object, "port");
	if (!obj)
		return -EINVAL;

	ret = hed_enc_port_from_json(encoder, obj);
	if (ret)
		return ret;

	return 0;
}



extern struct json_object * __hed_nonull(1) __nothrow __warn_result 
hed_dec_in_net_to_json(struct dpack_decoder * decoder)
{
	hed_assert(decoder);

	int ret;
	struct json_object *object;
	struct json_object *obj;

	object = json_object_new_object();
	if (!object)
		return NULL;

	obj = hed_decode_in_addr_to_json(decoder);
	if (!obj)
		goto error;

	ret = json_object_object_add(object, "addr", obj);
	if (ret)
		goto error;

	obj = hed_dec_in_pfx_to_json(decoder);
	if (!obj)
		goto error;

	ret = json_object_object_add(object, "prefix", obj);
	if (ret)
		goto error;

	return object;
error:
	json_object_put(object);
	return NULL;
}

extern int __hed_nonull(1, 2) __nothrow __warn_result 
hed_enc_in_net_from_json(struct dpack_encoder * encoder,
		    struct json_object * object)
{
	hed_assert(encoder);
	hed_assert(object);

	int ret;
	struct json_object *obj;
	size_t nb __unused;

	obj = json_object_object_get(object, "addr");
	if (!obj)
		return -EINVAL;

	ret = hed_encode_in_addr_from_json(encoder, obj);
	if (ret)
		return ret;

	obj = json_object_object_get(object, "prefix");
	if (!obj)
		return -EINVAL;

	ret = hed_enc_in_pfx_from_json(encoder, obj);
	if (ret)
		return ret;

	return 0;
}



extern struct json_object * __hed_nonull(1) __nothrow __warn_result 
hed_dec_in6_net_to_json(struct dpack_decoder * decoder)
{
	hed_assert(decoder);

	int ret;
	struct json_object *object;
	struct json_object *obj;

	object = json_object_new_object();
	if (!object)
		return NULL;

	obj = hed_decode_in6_addr_to_json(decoder);
	if (!obj)
		goto error;

	ret = json_object_object_add(object, "addr", obj);
	if (ret)
		goto error;

	obj = hed_dec_in6_pfx_to_json(decoder);
	if (!obj)
		goto error;

	ret = json_object_object_add(object, "prefix", obj);
	if (ret)
		goto error;

	return object;
error:
	json_object_put(object);
	return NULL;
}

extern int __hed_nonull(1, 2) __nothrow __warn_result 
hed_enc_in6_net_from_json(struct dpack_encoder * encoder,
		    struct json_object * object)
{
	hed_assert(encoder);
	hed_assert(object);

	int ret;
	struct json_object *obj;
	size_t nb __unused;

	obj = json_object_object_get(object, "addr");
	if (!obj)
		return -EINVAL;

	ret = hed_encode_in6_addr_from_json(encoder, obj);
	if (ret)
		return ret;

	obj = json_object_object_get(object, "prefix");
	if (!obj)
		return -EINVAL;

	ret = hed_enc_in6_pfx_from_json(encoder, obj);
	if (ret)
		return ret;

	return 0;
}

